export const publicationCategories = [
  { key: "journal", label: "Journal" },
  { key: "conference", label: "Conference" },
  { key: "bookChapter", label: "Book Chapter" },
  { key: "patent", label: "Patent" },
];

export const publicationFieldConfig = {
  journal: {
    columns: [
      ["title", "Title"],
      ["publicationName", "Journal Name"],
      ["publicationType", "Category"],
      ["impactFactor", "Impact Factor"],
      ["status", "Status"],
      ["dateOfCommunication", "Date of Communication"],
      ["isbn", "ISBN"],
      ["volumeNumber", "Vol No"],
      ["articleNumber", "Article No"],
      ["publishYear", "Publish Year"],
      ["link", "Link"],
    ],
  },
  conference: {
    columns: [
      ["title", "Title"],
      ["publicationName", "Conference Name"],
      ["scopusIndex", "Scopus Index"],
      ["dateOfConference", "Date of Conf."],
      ["venueOfConference", "Venue of Conf."],
      ["status", "Status"],
      ["dateOfCommunication", "Date of Communication"],
      ["isbn", "ISBN"],
      ["volumeNumber", "Vol No"],
      ["articleNumber", "Article No"],
      ["publishYear", "Publish Year"],
      ["link", "Link"],
    ],
  },
  bookChapter: {
    columns: [
      ["title", "Title"],
      ["publicationName", "Book Name"],
      ["scopusIndex", "Scopus Index"],
      ["publisher", "Publisher"],
      ["status", "Status"],
      ["dateOfCommunication", "Date of Communication"],
      ["isbn", "ISBN"],
      ["volumeNumber", "Vol No"],
      ["articleNumber", "Article No"],
      ["publishYear", "Publish Year"],
      ["link", "Link"],
    ],
  },
  patent: {
    columns: [
      ["title", "Title"],
      ["publicationName", "Patent Name"],
      ["applicationNumber", "Application No"],
      ["status", "Status"],
      ["dateOfFiled", "Date of Filed"],
      ["dateOfFer", "Date of FER"],
      ["dateOfGrant", "Date of Grant"],
      ["grantNumber", "Grant No"],
      ["isbn", "ISBN"],
      ["volumeNumber", "Vol No"],
      ["articleNumber", "Article No"],
      ["publishYear", "Publish Year"],
      ["link", "Link"],
    ],
  },
};

export const createEmptyPublication = (category) => ({
  category,
  title: "",
  publicationName: "",
  applicationNumber: "",
  scopusIndex: "",
  dateOfConference: "",
  venueOfConference: "",
  publisher: "",
  dateOfFiled: "",
  dateOfFer: "",
  dateOfGrant: "",
  grantNumber: "",
  publicationType: "",
  impactFactor: "",
  status: "",
  dateOfCommunication: "",
  isbn: "",
  volumeNumber: "",
  articleNumber: "",
  publishYear: "",
  link: "",
});
